build: Solve regex crate dependency conflict
Solved with:
```
cargo update -p regex --precise 1.5.6
```

Error was:
```
$ cargo check
    Updating git repository `https://github.com/kubewarden/policy-evaluator`
    Updating git repository `https://github.com/kubewarden/policy-fetcher`
    Updating crates.io index
    Updating git repository `https://github.com/sigstore/sigstore-rs`
error: failed to select a version for `regex`.
    ... required by package `validator v0.15.0`
    ... which satisfies dependency `validator = "^0.15"` of package `policy-evaluator v0.3.3 (https://github.com/kubewarden/policy-evaluator?tag=v0.3.3#ab9574c1)`
    ... which satisfies git dependency `policy-evaluator` of package `policy-server v0.3.0 (/home/vic/suse/kw/policy-server)`
versions that meet the requirements `^1` are: 1.5.5

all possible versions conflict with previously selected packages.

  previously selected package `regex v1.5.6`
    ... which satisfies dependency `regex = "^1.5.6"` of package `burrego v0.1.2 (https://github.com/kubewarden/policy-evaluator?tag=v0.3.3#ab9574c1)`
    ... which satisfies git dependency `burrego` of package `policy-evaluator v0.3.3 (https://github.com/kubewarden/policy-evaluator?tag=v0.3.3#ab9574c1)`
    ... which satisfies git dependency `policy-evaluator` of package `policy-server v0.3.0 (/home/vic/suse/kw/policy-server)`

failed to select a version for `regex` which could resolve this conflict
```