chore: Drop comment, cannot be implemented
`source: '{{ requiredEnv "RELEASE_VERSION" }}'` canot be used,
as it expects a `sourceid` and not a `source`:
```
ERROR: empty 'sourceid' for target "update_kubewarden_crds_helm_appversion"
```

Signed-off-by: Víctor Cuadrado Juan <vcuadradojuan@suse.de>