fix: Warn and continue when Sigstore TUF repository is broken
Allow Fulcio and Rekor data to be None. This means we will be missing
info from the transparency log, therefore not being able to validate
correct signatures, and giving false negatives.

Warn about it, and continue.

This protects us when upstream's Sigstore TUF repository has problems.

```
$ ./kwctl verify --verification-config-path=./../../e2e-tests/test-data/sigstore/verification-config-keyless.yml registry://ghcr.io/kubewarden/policies/capabilities-psp:v0.1.9

2022-07-19T09:57:04.387681Z  WARN kwctl: Cannot fetch TUF repository: TufError(ParseMetadata { role: Targets, source: Error("missing field `length`", line: 24, column: 4), backtrace: Backtrace(()) })
2022-07-19T09:57:04.387762Z  WARN policy_fetcher::verify: Sigstore Verifier created without Fulcio data: keyless signatures are going to be discarded because they cannot be verified
2022-07-19T09:57:04.387771Z  WARN policy_fetcher::verify: Sigstore Verifier created without Rekor data: transparency log data won't be used
2022-07-19T09:57:04.387781Z  WARN policy_fetcher::verify: Sigstore capabilities are going to be limited
Error: Policy registry://ghcr.io/kubewarden/policies/capabilities-psp:v0.1.9 cannot be validated
No Signature Layer passed verification
```